//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 04:01:32 PM CDT 
//


package com.github.bwsoft.iris.message.sbe.fixsbe.rc4;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="types" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded">
 *                   &lt;element name="type" type="{http://fixprotocol.io/sbe/rc4}encodedDataType"/>
 *                   &lt;element name="composite" type="{http://fixprotocol.io/sbe/rc4}compositeDataType"/>
 *                   &lt;element name="enum" type="{http://fixprotocol.io/sbe/rc4}enumType"/>
 *                   &lt;element name="set" type="{http://fixprotocol.io/sbe/rc4}setType"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://fixprotocol.io/sbe/rc4}message" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="package" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="semanticVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="byteOrder" default="littleEndian">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="bigEndian"/>
 *             &lt;enumeration value="littleEndian"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="headerType" type="{http://fixprotocol.io/sbe/rc4}symbolicName_t" default="messageHeader" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "types",
    "message"
})
@XmlRootElement(name = "messageSchema")
public class MessageSchema {

    @XmlElement(required = true)
    protected List<MessageSchema.Types> types;
    @XmlElement(namespace = "http://fixprotocol.io/sbe/rc4", required = true)
    protected List<BlockType> message;
    @XmlAttribute(name = "package")
    protected String _package;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer id;
    @XmlAttribute(name = "version", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger version;
    @XmlAttribute(name = "semanticVersion")
    protected String semanticVersion;
    @XmlAttribute(name = "description")
    protected String description;
    @XmlAttribute(name = "byteOrder")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String byteOrder;
    @XmlAttribute(name = "headerType")
    protected String headerType;

    /**
     * Gets the value of the types property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the types property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MessageSchema.Types }
     * 
     * 
     */
    public List<MessageSchema.Types> getTypes() {
        if (types == null) {
            types = new ArrayList<MessageSchema.Types>();
        }
        return this.types;
    }

    /**
     * Gets the value of the message property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the message property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BlockType }
     * 
     * 
     */
    public List<BlockType> getMessage() {
        if (message == null) {
            message = new ArrayList<BlockType>();
        }
        return this.message;
    }

    /**
     * Gets the value of the package property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackage() {
        return _package;
    }

    /**
     * Sets the value of the package property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackage(String value) {
        this._package = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersion(BigInteger value) {
        this.version = value;
    }

    /**
     * Gets the value of the semanticVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSemanticVersion() {
        return semanticVersion;
    }

    /**
     * Sets the value of the semanticVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSemanticVersion(String value) {
        this.semanticVersion = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the byteOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getByteOrder() {
        if (byteOrder == null) {
            return "littleEndian";
        } else {
            return byteOrder;
        }
    }

    /**
     * Sets the value of the byteOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setByteOrder(String value) {
        this.byteOrder = value;
    }

    /**
     * Gets the value of the headerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeaderType() {
        if (headerType == null) {
            return "messageHeader";
        } else {
            return headerType;
        }
    }

    /**
     * Sets the value of the headerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeaderType(String value) {
        this.headerType = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded">
     *         &lt;element name="type" type="{http://fixprotocol.io/sbe/rc4}encodedDataType"/>
     *         &lt;element name="composite" type="{http://fixprotocol.io/sbe/rc4}compositeDataType"/>
     *         &lt;element name="enum" type="{http://fixprotocol.io/sbe/rc4}enumType"/>
     *         &lt;element name="set" type="{http://fixprotocol.io/sbe/rc4}setType"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "typeOrCompositeOrEnum"
    })
    public static class Types {

        @XmlElements({
            @XmlElement(name = "type", type = EncodedDataType.class),
            @XmlElement(name = "composite", type = CompositeDataType.class),
            @XmlElement(name = "enum", type = EnumType.class),
            @XmlElement(name = "set", type = SetType.class)
        })
        protected List<Object> typeOrCompositeOrEnum;

        /**
         * Gets the value of the typeOrCompositeOrEnum property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the typeOrCompositeOrEnum property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTypeOrCompositeOrEnum().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EncodedDataType }
         * {@link CompositeDataType }
         * {@link EnumType }
         * {@link SetType }
         * 
         * 
         */
        public List<Object> getTypeOrCompositeOrEnum() {
            if (typeOrCompositeOrEnum == null) {
                typeOrCompositeOrEnum = new ArrayList<Object>();
            }
            return this.typeOrCompositeOrEnum;
        }

    }

}
