//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.13 at 10:17:36 PM CDT 
//


package org.fix.sbe;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Variable length data consists of a pair elements:
 *                 length field and data field. Length of varData field is transmitted
 *                 in length field.
 *             
 * 
 * <p>Java class for varDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="varDataType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fixprotocol.org/ns/simple/1.0}compositeDataType">
 *       &lt;sequence>
 *         &lt;element name="length" type="{http://www.fixprotocol.org/ns/simple/1.0}encodedDataType"/>
 *         &lt;element name="varData" type="{http://www.fixprotocol.org/ns/simple/1.0}encodedDataType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "varDataType")
public class VarDataType
    extends CompositeDataType
{


}
