/*******************************************************************************
 * Copyright 2016 bwsoft and others
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.13 at 10:17:36 PM CDT 
//


package org.fix.sbe;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Standard message header layout
 *             
 * 
 * <p>Java class for messageHeaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="messageHeaderType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fixprotocol.org/ns/simple/1.0}compositeDataType">
 *       &lt;sequence>
 *         &lt;element name="blockLength" type="{http://www.fixprotocol.org/ns/simple/1.0}encodedDataType"/>
 *         &lt;element name="templateId" type="{http://www.fixprotocol.org/ns/simple/1.0}encodedDataType"/>
 *         &lt;element name="version" type="{http://www.fixprotocol.org/ns/simple/1.0}encodedDataType"/>
 *         &lt;element name="reserved" type="{http://www.fixprotocol.org/ns/simple/1.0}encodedDataType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "messageHeaderType")
public class MessageHeaderType
    extends CompositeDataType
{


}
