/*******************************************************************************
 * Copyright 2016 bwsoft and others
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.13 at 10:17:36 PM CDT 
//


package org.fix.sbe;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.fix.sbe package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MessageField_QNAME = new QName("", "field");
    private final static QName _MessageData_QNAME = new QName("", "data");
    private final static QName _MessageGroup_QNAME = new QName("", "group");
    private final static QName _EnumTypeValidValue_QNAME = new QName("", "validValue");
    private final static QName _SetTypeChoice_QNAME = new QName("", "choice");
    private final static QName _CompositeDataTypeComposite_QNAME = new QName("", "composite");
    private final static QName _CompositeDataTypeType_QNAME = new QName("", "type");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.fix.sbe
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MessageSchema }
     * 
     */
    public MessageSchema createMessageSchema() {
        return new MessageSchema();
    }

    /**
     * Create an instance of {@link MessageSchema.Types }
     * 
     */
    public MessageSchema.Types createMessageSchemaTypes() {
        return new MessageSchema.Types();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link FieldType }
     * 
     */
    public FieldType createFieldType() {
        return new FieldType();
    }

    /**
     * Create an instance of {@link GroupType }
     * 
     */
    public GroupType createGroupType() {
        return new GroupType();
    }

    /**
     * Create an instance of {@link MessageHeaderType }
     * 
     */
    public MessageHeaderType createMessageHeaderType() {
        return new MessageHeaderType();
    }

    /**
     * Create an instance of {@link ValidValue }
     * 
     */
    public ValidValue createValidValue() {
        return new ValidValue();
    }

    /**
     * Create an instance of {@link CompositeDataType }
     * 
     */
    public CompositeDataType createCompositeDataType() {
        return new CompositeDataType();
    }

    /**
     * Create an instance of {@link EnumType }
     * 
     */
    public EnumType createEnumType() {
        return new EnumType();
    }

    /**
     * Create an instance of {@link EncodedDataType }
     * 
     */
    public EncodedDataType createEncodedDataType() {
        return new EncodedDataType();
    }

    /**
     * Create an instance of {@link SetType }
     * 
     */
    public SetType createSetType() {
        return new SetType();
    }

    /**
     * Create an instance of {@link Choice }
     * 
     */
    public Choice createChoice() {
        return new Choice();
    }

    /**
     * Create an instance of {@link VarDataType }
     * 
     */
    public VarDataType createVarDataType() {
        return new VarDataType();
    }

    /**
     * Create an instance of {@link GroupSizeType }
     * 
     */
    public GroupSizeType createGroupSizeType() {
        return new GroupSizeType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FieldType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "field", scope = Message.class)
    public JAXBElement<FieldType> createMessageField(FieldType value) {
        return new JAXBElement<FieldType>(_MessageField_QNAME, FieldType.class, Message.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FieldType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "data", scope = Message.class)
    public JAXBElement<FieldType> createMessageData(FieldType value) {
        return new JAXBElement<FieldType>(_MessageData_QNAME, FieldType.class, Message.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GroupType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "group", scope = Message.class)
    public JAXBElement<GroupType> createMessageGroup(GroupType value) {
        return new JAXBElement<GroupType>(_MessageGroup_QNAME, GroupType.class, Message.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "validValue", scope = EnumType.class)
    public JAXBElement<ValidValue> createEnumTypeValidValue(ValidValue value) {
        return new JAXBElement<ValidValue>(_EnumTypeValidValue_QNAME, ValidValue.class, EnumType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Choice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "choice", scope = SetType.class)
    public JAXBElement<Choice> createSetTypeChoice(Choice value) {
        return new JAXBElement<Choice>(_SetTypeChoice_QNAME, Choice.class, SetType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompositeDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "composite", scope = CompositeDataType.class)
    public JAXBElement<CompositeDataType> createCompositeDataTypeComposite(CompositeDataType value) {
        return new JAXBElement<CompositeDataType>(_CompositeDataTypeComposite_QNAME, CompositeDataType.class, CompositeDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EncodedDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "type", scope = CompositeDataType.class)
    public JAXBElement<EncodedDataType> createCompositeDataTypeType(EncodedDataType value) {
        return new JAXBElement<EncodedDataType>(_CompositeDataTypeType_QNAME, EncodedDataType.class, CompositeDataType.class, value);
    }

}
