//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.29 at 08:51:30 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://fixprotocol.io/2016/sbe")
package com.github.bwsoft.iris.message.sbe.fixsbe;
